spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionale_ore_cinepark
    username: postgres
    password: Pietro2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
